import { NextRequest, NextResponse } from "next/server";
import path from "path";
import prettier from "prettier";
import fs from "fs";

export async function POST(req: NextRequest) {
  const TARGET_DIR = path.join(process.cwd(), "contracts");
  try {
    const data = await req.json();

    const generatedContractComment = `/**
* This file is autogenerated by Scaffold-Stark.
* You should not edit it manually or your changes might be overwritten.
*/`;

    const fileContent = await prettier.format(
      `${generatedContractComment}\n\nconst configExternalContracts = ${JSON.stringify(data)} as const;\n\nexport default configExternalContracts;`,
      {
        parser: "typescript",
      },
    );

    fs.writeFileSync(
      path.join(TARGET_DIR, "configExternalContracts.ts"),
      fileContent,
    );

    return NextResponse.json({ success: true });
  } catch (error) {
    console.error(error);
    return NextResponse.json(
      { error: "Failed to write contract file" },
      { status: 500 },
    );
  }
}
