/**
 * This file is autogenerated by Scaffold-Stark.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-stark/contract";

const deployedContracts = {
  devnet: {
    HelloStarknet: {
      address:
        "0x04f33e09ca87b41c65de855e778b645786c6155aff9ffbe52905e4689b430d0e",
    },
    SimpleStorage: {
      address:
        "0x073ef80989bee4acf22857c9909b301ebfae763138b7530c4509ea2c00f6e0c2",
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
