/**
 * This file is autogenerated by Scaffold-Stark.
 * You should not edit it manually or your changes might be overwritten.
 */

import {
  devnetEthClassHash,
  universalEthAddress,
  universalStrkAddress,
  universalClassHash,
  universalAbi,
} from "./Constants";

const preDeployedContracts = {
  devnet: {
    Eth: {
      address: universalEthAddress,
      abi: universalAbi,
      classHash: devnetEthClassHash,
    },
    Strk: {
      address: universalStrkAddress,
      abi: universalAbi,
      classHash: universalClassHash,
    },
  },
  sepolia: {
    Eth: {
      address: universalEthAddress,
      abi: universalAbi,
      classHash: universalClassHash,
    },
    Strk: {
      address: universalStrkAddress,
      abi: universalAbi,
      classHash: universalClassHash,
    },
  },
  mainnet: {
    Eth: {
      address: universalEthAddress,
      abi: universalAbi,
      classHash: universalClassHash,
    },
    Strk: {
      address: universalStrkAddress,
      abi: universalAbi,
      classHash: universalClassHash,
    },
  },
} as const;

export default preDeployedContracts;
