import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ScaffoldStarkAppWithProviders } from "~~/src/app/components/ScaffoldStarkAppWithProviders";
import '@radix-ui/themes/styles.css';
import { Theme } from '@radix-ui/themes';
import Header from "./components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <Theme>
        <ScaffoldStarkAppWithProviders>
          <Header />
          {children}
        </ScaffoldStarkAppWithProviders>
        </Theme>
      </body>
    </html>
  );
}
