import fs from "fs";
import path from "path";
import prettier from "prettier";

const generatedContractComment = `/**
 * This file is autogenerated by Scaffold-Stark.
 * You should not edit it manually or your changes might be overwritten.
 */`;
const TARGET_DIR = path.join(__dirname, "../../../nextjs/contracts");
function resetDeployedContracts(): void {
  if (!fs.existsSync(TARGET_DIR)) {
    fs.mkdirSync(TARGET_DIR);
  }

  fs.writeFileSync(
    path.join(TARGET_DIR, "deployedContracts.ts"),
    prettier.format(
      `${generatedContractComment}\n\nconst deployedContracts = {} as const;\n\nexport default deployedContracts;`,
      {
        parser: "typescript",
      }
    )
  );
}
resetDeployedContracts();
