FROM starknetfoundation/starknet-dev:2.9.2

USER root

RUN apt-get update && \
    apt-get install -y curl sudo && \
    rm -rf /var/lib/apt/lists/*

RUN curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash - && \
    sudo apt-get update && \
    sudo apt-get install -y nodejs && \
    sudo rm -rf /var/lib/apt/lists/*

RUN npm install -g yarn@1.22.19

WORKDIR /app

COPY . .

RUN yarn install

WORKDIR /app/packages/snfoundry