# Get the latest version of Playwright
FROM mcr.microsoft.com/playwright:focal

# Set the work directory
WORKDIR /app

# Set the environment path to node_modules/.bin
ENV PATH /app/node_modules/.bin:$PATH

# Copy package files
COPY ui-automation/package.json /app/
COPY ui-automation/tests/ /app/tests/
COPY ui-automation/tsconfig.json /app/
COPY ui-automation/playwright.config.ts /app/
# Install Node dependencies
RUN npm install
