#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Navigate to the root directory of your repository
cd $(git rev-parse --show-toplevel)

# Use git status --porcelain to check for changes in the local-devnet directory
CHANGED=$(git status --porcelain | grep "packages/snfoundry/local-devnet")

# Check if there are changes
if [ ! -z "$CHANGED" ]; then
  echo "Error: Changes detected in packages/snfoundry/local-devnet"
  exit 1
fi

npm run format:check
