name: Sync Main to v3-bulletproof-contract for E2E Tests

on:
  push:
    branches:
      - main

jobs:
  merge:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge main into v3-bulletproof-contract
        run: |
          git remote update
          git checkout v3-bulletproof-contract
          git merge origin/main --no-edit || echo "No changes to merge"
          git push origin v3-bulletproof-contract
