name: Scaffold Stark React Native Sync and Update

on:
  pull_request:
    types: [closed]
    branches: [main]
  workflow_dispatch:

jobs:
  check_commit:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      SHOULD_RUN: ${{ steps.check_commit.outputs.SHOULD_RUN }}
    steps:
      - name: Checkout Files
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ORG_GITHUB_TOKEN }}

      - name: check if skip ci
        id: check_commit
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          if [[ "$COMMIT_MESSAGE" == *"[skip ci]"* ]]; then
            echo "SHOULD_RUN=false" >> "$GITHUB_OUTPUT"
          else
            echo "SHOULD_RUN=true" >> "$GITHUB_OUTPUT"
          fi

  sync-speedrun:
    needs: check_commit
    if: ${{ needs.check_commit.outputs.SHOULD_RUN != 'false' }}
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v4
        with:
          repository: Scaffold-Stark/scaffold-stark-2
          token: ${{ secrets.ORG_GITHUB_TOKEN }}
          path: source_repo

      - name: Checkout Destination Repository
        uses: actions/checkout@v4
        with:
          repository: Scaffold-Stark/scaffold-stark-rn
          token: ${{ secrets.ORG_GITHUB_TOKEN }}
          path: destination_repo
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Sync Base Branch
        run: |
          cd destination_repo
          git checkout develop
          cp -f ../source_repo/.tool-versions ./.tool-versions
          rsync -av ../source_repo/packages/snfoundry/ ./packages/snfoundry/
          if ! git apply -p1 ./.github/rn.patch; then
            echo "Failed to apply rn.patch. Failing CI."
            exit 1
          fi

          git add .
          git commit -m "chore: sync files from scaffold-stark-2"
          git push origin develop

      - name: Notify Slack on Success
        if: success()
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          slack-message: "Successfully synced scaffold-stark-2 changes to scaffold-stark-rn repository main branch."
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Notify Slack on Failure
        if: failure()
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          slack-message: "Failed to sync scaffold-stark-2 changes to scaffold-stark-rn repository."
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
